language: "Chinese"
model_name: "chn-1"
batch_size: 16
lr: 0.001
num_layers: 1
hidden_size: 256
dropout: 0.5
epochs: 10
seed: 12345
data_dir: "./data/Chinese/"
ckpt_dir: "./ckpt/"
train_file: "train.txt"
dev_file: "validation.txt"
test_file: "validation.txt"
output_file: "output.txt"

tokenizer: "bert-base-chinese"
max_length: 128
num_labels: 33
label2id:
  O: 0
  B-NAME: 1
  M-NAME: 2
  E-NAME: 3
  S-NAME: 4
  B-CONT: 5
  M-CONT: 6
  E-CONT: 7
  S-CONT: 8
  B-EDU: 9
  M-EDU: 10
  E-EDU: 11
  S-EDU: 12
  B-TITLE: 13
  M-TITLE: 14
  E-TITLE: 15
  S-TITLE: 16
  B-ORG: 17
  M-ORG: 18
  E-ORG: 19
  S-ORG: 20
  B-RACE: 21
  M-RACE: 22
  E-RACE: 23
  S-RACE: 24
  B-PRO: 25
  M-PRO: 26
  E-PRO: 27
  S-PRO: 28
  B-LOC: 29
  M-LOC: 30
  E-LOC: 31
  S-LOC: 32
id2label:
  0: "O"
  1: "B-NAME"
  2: "M-NAME"
  3: "E-NAME"
  4: "S-NAME"
  5: "B-CONT"
  6: "M-CONT"
  7: "E-CONT"
  8: "S-CONT"
  9: "B-EDU"
  10: "M-EDU"
  11: "E-EDU"
  12: "S-EDU"
  13: "B-TITLE"
  14: "M-TITLE"
  15: "E-TITLE"
  16: "S-TITLE"
  17: "B-ORG"
  18: "M-ORG"
  19: "E-ORG"
  20: "S-ORG"
  21: "B-RACE"
  22: "M-RACE"
  23: "E-RACE"
  24: "S-RACE"
  25: "B-PRO"
  26: "M-PRO"
  27: "E-PRO"
  28: "S-PRO"
  29: "B-LOC"
  30: "M-LOC"
  31: "E-LOC"
  32: "S-LOC"

sort_labels:
  - "O"
  - "B-NAME"
  - "M-NAME"
  - "E-NAME"
  - "S-NAME"
  - "B-CONT"
  - "M-CONT"
  - "E-CONT"
  - "S-CONT"
  - "B-EDU"
  - "M-EDU"
  - "E-EDU"
  - "S-EDU"
  - "B-TITLE"
  - "M-TITLE"
  - "E-TITLE"
  - "S-TITLE"
  - "B-ORG"
  - "M-ORG"
  - "E-ORG"
  - "S-ORG"
  - "B-RACE"
  - "M-RACE"
  - "E-RACE"
  - "S-RACE"
  - "B-PRO"
  - "M-PRO"
  - "E-PRO"
  - "S-PRO"
  - "B-LOC"
  - "M-LOC"
  - "E-LOC"
  - "S-LOC"