language: "English"
model_name: "eng-1"
batch_size: 16
lr: 0.005
num_layers: 3
hidden_size: 256
dropout: 0.5
epochs: 500
seed: 70
data_dir: "./data/English/"
ckpt_dir: "./ckpt/"
train_file: "train.txt"
dev_file: "validation.txt"
test_file: "validation.txt"
output_file: "output.txt"

tokenizer: "prajjwal1/bert-small"
# tokenizer: "dbmdz/bert-large-cased-finetuned-conll03-english"
max_length: 128
num_labels: 9
label2id:
  O: 0
  B-PER: 1
  I-PER: 2
  B-ORG: 3
  I-ORG: 4
  B-LOC: 5
  I-LOC: 6
  B-MISC: 7
  I-MISC: 8
id2label:
  0: "O"
  1: "B-PER"
  2: "I-PER"
  3: "B-ORG"
  4: "I-ORG"
  5: "B-LOC"
  6: "I-LOC"
  7: "B-MISC"
  8: "I-MISC"

sort_labels:
  - "O"
  - "B-PER"
  - "I-PER"
  - "B-ORG"
  - "I-ORG"
  - "B-LOC"
  - "I-LOC"
  - "B-MISC"
  - "I-MISC"