language: "English"
model_name: "BERT"
batch_size: 16
lr: 0.001
num_layers: 6
hidden_size: 768
dropout: 0.1
epochs: 10
device: 0
seed: 12345
data_dir: "./data/$language/"
ckpt_dir: "./ckpt/"
train_file: "train.txt"
dev_file: "validation.txt"
test_file: "test.txt"
output_file: "output.txt"

tokenizer: "BERTTokenizer"
max_length: 128
num_labels: 9
label2id:
  O: 0
  B-PER: 1
  I-PER: 2
  B-ORG: 3
  I-ORG: 4
  B-LOC: 5
  I-LOC: 6
  B-MISC: 7
  I-MISC: 8
id2label:
  0: "O"
  1: "B-PER"
  2: "I-PER"
  3: "B-ORG"
  4: "I-ORG"
  5: "B-LOC"
  6: "I-LOC"
  7: "B-MISC"
  8: "I-MISC"

